### ISSUE TITLE
GenDBCX

### ISSUE THREAD

**Issue by lscheffler** [VFPX/GenDBC#1]
High Doug,

I have a bit trouble with a corrupted DBC and run over GenDBCX.

I see here there is stuff changed that looks like your code, but not in GenDBCX. And I found an issue with the recreation of the RIINFO field of the database. Are you able to maintain this? I have a copy of GenDBCX with latest change as of 1997.10.01.

**Comment by lscheffler** [comment]
ok, if found something newer on Ed Leafes site recent as 1998.07.20. But this looks still like w/o the datatypes ...

**Comment by DougHennig** [comment]
The PRG in this repository is the same as the latest one I have. Also, I haven't looked at this code in nearly 20 years so you know this code almost as well as I do!

**Comment by lscheffler** [comment]
It is basically about GenDBC **X**, to put our latest changes into that.  And fix the other problem. Let's if I fun to it. :)

**Comment by lscheffler** [comment]
### GenDBCX
I have fixed, GenDBCX - so far. I just need to learn a bit about versions prior VFP6.   
And then we might think to put it to VFPX, I asked Ed for permission.


### GenDBC
For the problem with th RIINFO. I think it is overkill to fork and merge this. Should I simple send you a fixed version and you push it to this repo?

**Comment by DougHennig** [comment]
Yes, you can send it to me.
